### ISSUE TITLE
Ensure persistence of test studies on Movebank

### ISSUE THREAD

**Issue by julietcohen** [syanco/human_mobility_wildlife#11]
There are some temporary/test datasets such as Hawley's black bear dataset that will only exist on Movebank for 90 days, and after this period need to be recreated or switched to Research. The Movebank documentation specifies that Data Managers will receive [notifications](https://www.movebank.org/cms/movebank-content/notifications) on Movebank and by e-mail sent from support@movebank.org with reminders three days and one day before a study is deleted.

Once a study is in its final form and we're sure we're using it in our MS, we can update our sheets and database with the final study ID, since this changes with each test version of the study.

**Comment by syanco** [comment]
This is all true but let's make sure we need to actually worry about this.  If the data is stored as a temp study and the authors don't share publically or they share via some repo other than movebank, then i don't think there's any study id to update.  Similarly, I guess it's worthwhile to update any study_id's that change, but not essential for the scripts to run.

**Comment by julietcohen** [comment]
Thanks, Scott! That makes sense.

**Comment by julietcohen** [comment]
In addition to noting the idea to update study ID's as they change for tmp studies, I made this issue because as we continue to work with the data and reference metadata from tmp studies, we'll want to create new tmp studies for the same datasets just to keep the info up on Movebank, and I assume it'll be easier to create a new study with the same info before the last version of the study is removed

**Comment by julietcohen** [comment]
After talking to Ruth, it's clear that the tmp studies on Movebank are not important to update for another 90 days as long as we already have the data in the database file. Closing this issue now, but can be re-opened if necessary.
