### ISSUE TITLE
Determine status of branch: `13-add-ssf-analyses`

### ISSUE THREAD

**Issue by julietcohen** [syanco/human_mobility_wildlife#4]
This branch has 345 commits that can be merged into main, and contains more _recent_ commits than main. 1 commit from main is missing from this branch. Should this branch be merged into main?

**Comment by syanco** [comment]
Yes it can be at this point and is a good example of my sloppy half-use of branches...

**Comment by julietcohen** [comment]
Thank you @syanco! Was this branch used to process the species datasets? If so, I'll merge the branch into main _before_ I make the first release. 

I'm planning to make an initial release for the current status of the repo that was used to process the first round of species datasets. Then I'll modify the code to process the new species datasets and release that second version so we can point to both in the new manuscript section "Data Availability and Code Availability", assuming we do _not_ rerun the original species with the new code. If we _do_ rerun all species with the new code, we will only reference the second version in our methods.

**Comment by julietcohen** [comment]
This branch is the one that was used to process the original species datasets. It should eventually be merged into main, but there is no rush for this.

It is TBD if we will choose to make the second release for just the "part 2" (new species) workflow, or if it will be a more generalized workflow
