### ISSUE TITLE
Query Movebank for new species datasets

### ISSUE THREAD

**Issue by julietcohen** [syanco/human_mobility_wildlife#9]
Are there any more species datasets we can use in our analysis? We can run a query using the `move` package. Scott shared an example script of a similar process for a different paper. The code should be adjusted for this project:
- data for 2019 & 2020
- birds and mammals
- in the US

**Comment by julietcohen** [comment]
If this query turns out to be useful, it may be a good idea to create a generalized version of this query to serve as a tool for various research projects, since it was useful for Scott & collaborators' other paper for bird specific research.

**Comment by julietcohen** [comment]
For any _new_ species/studies that are returned from this new query and are _not_ ones that we have already used in the analysis (the last submitted version of the manuscript) _and_ that we have _not_ already flagged in the "potential new datasets" spreadsheet, I will create a new tab in the "potential new datasets" spreadsheet and add them there

**Comment by julietcohen** [comment]
This has been moved up in priority to be completed in the next week or so. Note that Scott has already queried for birds, so mine will just be for mammals. I may or may not have the ability to properly query for studies that at least contain data for the 2 years of interest so may just have to query without a time limitation and manually sift through the output studies for this after

**Comment by julietcohen** [comment]
Following Scott's bird query for MB datasets:

- Scott used an external bird database, Avonet crosswalk, to load a comprehensive list of all relevant species. He then used filtered Movebank studies to retain studies for species within that bird list. Similarly, I should use a North American mammal database to filter the Movebank studies for only those species. I found one [here](https://www.mammaldiversity.org/index.html). I also looked into using the[ ITIS database](https://itis.gov/), which come in SQLite format and is referenced for several attributes within the Movebank dictionary, but ITIS did not seem to be useful for this purpose as the Movebank studies data does not have the [`tsn`](https://vocab.nerc.ac.uk/collection/MVB/current/MVB000277/) attribute to link to this database.
- He then used the lat and long of the reference point for the dataset to filter for only studies in North America, using the polygons for North America from the `rnaturalearth` package. I should do the same but only for the USA.
- One additional step I'm adding is to filter the database based on the first and last timestamps. Since we want data between January and July 2019 & 2020, I should filter the starting timestamp to be before July 1 2019 and the final timestamp after January 1 2020. This retains all studies that could have continuous data for the relevant time period, even if the studies also have data beyond our desired start and end dates. 
- I also added a filter for studies that have more than 4 individuals

**Comment by syanco** [comment]
FYI - i would be surprised if you had many tax that weren't birds and mammals on MB.  You can probably skip the taxonomic step and we'll just evaluate manually.

**Comment by julietcohen** [comment]
Yeah that's a good point. Even with limiting the query to just the USA mammals list, I got a lot of results - 127 studies. I'm sure that not all these studies fit our temporal criteria since my filter for this was only based on first and last timestamps, rather than checking all event data for enough points within the months of interest. I started a loop to test downloading the event data for all 127 studies. Some are downloading, but many don't have data available (unsurprisingly)

**Comment by julietcohen** [comment]
<details>
  <summary>query_MB_mammals.R</summary>
  
 ```{r}
#### Query Movebank for mammals in USA, 2019-2020 ####

library(tidyverse)
library(glue)
library(rnaturalearth)
library(sf)
library(move)
library(yaml)

# Movebank data file
.datmbPF <- "/Users/juliet/Documents/OliverLab/covid_paper/new_spp_db/MB_query/data/direct-read.csv"
# mammal spp database from https://www.mammaldiversity.org/index.html
mammal_spp <- "/Users/juliet/Documents/OliverLab/covid_paper/new_spp_db/MB_query/data/MDD/MDD_v1.13_6753species.csv"

# load movebank studies file 
# downloaded via API at https://www.movebank.org/movebank/service/direct-read?entity_type=study
mb_studies <- read_csv(.datmbPF)

mammals <- read_csv(mammal_spp) %>% 
            mutate(sciName = str_replace_all(sciName, "_", " "))

# load United States of America polygon
usa <- ne_countries(scale = "medium", returnclass = "sf") %>%
          filter(name == "United States of America")

# filter to mammals only
mb_mammals <- mb_studies %>% 
  filter(taxon_ids %in% mammals$sciName)

# filter to United States of America only
bb <- st_bbox(usa)
mb_mammals_usa <- mb_mammals %>% 
                    filter(main_location_lat > bb["ymin"] & main_location_lat < bb["ymax"] &
                    main_location_long > bb["xmin"] & main_location_long < bb["xmax"])

# filter based on timestamps:
# earliest timestamp must be before 01/07/2019,
# final timestamp must be after 01/01/2020
mb_mammals_usa_covid <- mb_mammals_usa %>% 
                        filter(timestamp_first_deployed_location <= as.POSIXct("2019-07-01"),
                               timestamp_last_deployed_location >= as.POSIXct("2020-01-01"),
                               number_of_individuals > 4) 

# save as CSV
write_csv(mb_mammals_usa_covid, file = "/Users/juliet/Documents/OliverLab/covid_paper/new_spp_db/MB_query/studies_returned.csv")

studies_list <- mb_mammals_usa_covid$id
# save as txt file
cat(studies_list, file = "/Users/juliet/Documents/OliverLab/covid_paper/new_spp_db/MB_query/studies_returned.txt", sep = "\n")

print("Script complete")



  ```
</details>

**Comment by julietcohen** [comment]
Ruth noted that of the returned species, we will consider adding wolverine, musk ox, and caribou based on what we already have. I noted these in the [issue](https://github.com/syanco/human_mobility_wildlife/issues/3#issue-2562789604) for the new database. Feel free to reopen this issue if we want to look deeper or redo the query.

**Comment by julietcohen** [comment]
Note: the same query as above without the filter for mammals (linked above) results in 950 movebank studies for birds, mammals, and whatever other species people put trackers on. 

<details>
  <summary>query_MB.R</summary>
  
 ```{r}
#### Query Movebank for mammals in USA, 2019-2020 ####

library(tidyverse)
library(glue)
library(rnaturalearth)
library(sf)
library(move)
library(yaml)

# Movebank data file
.datmbPF <- "/Users/juliet/Documents/OliverLab/covid_paper/new_spp_db/MB_query/data/direct-read.csv"

# load movebank studies file 
# downloaded via API at https://www.movebank.org/movebank/service/direct-read?entity_type=study
mb_studies <- read_csv(.datmbPF)

# load United States of America polygon
usa <- ne_countries(scale = "medium", returnclass = "sf") %>%
          filter(name == "United States of America")

# filter to United States of America only
bb <- st_bbox(usa)


mb_usa <- mb_studies %>%
  filter(main_location_lat > bb["ymin"] & main_location_lat < bb["ymax"] &
         main_location_long > bb["xmin"] & main_location_long < bb["xmax"])

# filter based on timestamps:
# earliest timestamp must be before 01/07/2019,
# final timestamp must be after 01/01/2020

mb_usa_covid <- mb_usa %>%
                filter(timestamp_first_deployed_location <= as.POSIXct("2019-07-01"),
                       timestamp_last_deployed_location >= as.POSIXct("2020-01-01"),
                       number_of_individuals > 4)

# save as CSV
write_csv(mb_usa_covid, file = "/Users/juliet/Documents/OliverLab/covid_paper/new_spp_db/MB_query/studies_returned_all.csv")

print("Script complete")
  ```
</details>
